services:
  - type: web
    name: devtinder-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false        # set manually in Render dashboard
      - key: jwt_secret
        sync: false        # set manually in Render dashboard
      - key: CLIENT_URL
        sync: false        # set to your Netlify URL after deployment
